@startuml
class com.pluralsight.deli.models.Sandwich {
}
class com.pluralsight.deli.app.DeliShopApp {
}
abstract class com.pluralsight.deli.models.Order {
- String customerName
- String customerEmail
- Sandwich customerSandwich
+ {abstract}double getTotalCost()
+ {abstract}String getOrderDetails()
}


@enduml